server:
  port: 8000
Spring:
  application:
    name: gateway-service
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: authService
          uri:
            "lb://AUTH-SERVICE"
          predicates:
            - Path=/api/v1/auth/**
        - id: waitingService
          uri:
            "lb://WAITING-SERVICE"
          predicates:
            - Path=/api/v1/waiting/**
        - id: storeService
          uri:
            "lb://STORE-SERVICE"
          predicates:
            - Path=/api/v1/store/**
        - id: reservationService
          uri:
            "lb://RESERVATION-SERVICE"
          predicates:
            - Path=/api/v1/reservation/**