server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: memberService
          uri:
            "lb://MEMBER-SERVICE"
          predicates:
            - Path=/api/v1/member/**
        - id: waitingService
          uri:
            "lb://WAITING-SERVICE"
          predicates:
            - Path=/api/v1/waiting/**
        - id: storeService
          uri:
            "lb://STORE-SERVICE"
          predicates:
            - Path=/api/v1/store/**
        - id: reservationService
          uri:
            "lb://RESERVATION-SERVICE"
          predicates:
            - Path=/api/v1/reservation/**
        - id: reviewService
          uri:
            "lb://REVIEW-SERVICE"
          predicates:
            - Path=/api/v1/reviews/**
        - id: customerService
          uri:
            "lb://CUSTOMER-SERVICE"
          predicates:
            - Path=/api/v1/customers/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
